name: enterprise_state_inspector
description: Developer overlay for inspecting Riverpod and Bloc state changes in Flutter apps.
version: 0.1.0-dev.1
homepage: http://tienenwu.me/
repository: https://github.com/tienenwu/enterprise_state_inspector
issue_tracker: https://github.com/tienenwu/enterprise_state_inspector/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.3.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
